# Generated by Django 5.2.2 on 2025-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
